sources := \
	dau/Dau.cpp \
	dau/DauController.cpp \
	dau/DauGainManager.cpp \
	dau/DauInputManager.cpp \
	dau/DauLutManager.cpp \
	dau/DauSequenceBuilder.cpp \
	dau/DauSignalHandler.cpp \
	dau/DauSseManager.cpp \
	dau/DauTbfManager.cpp \
	dau/ColorAcq.cpp \
	dau/ColorAcqLinear.cpp \
	dau/MmodeAcq.cpp \
	dau/DauArrayTest.cpp \
	dau/DopplerAcq.cpp \
	dau/DopplerAcqLinear.cpp \
	dau/CWAcq.cpp \
	ImageProcessing/ImageProcessor.cpp \
	ImageProcessing/Autoecho.cpp \
	ImageProcessing/Colorflow.cpp \
	ImageProcessing/AutoGainProcess.cpp \
	ImageProcessing/DeInterleaveProcess.cpp \
	ImageProcessing/DeInterleaveMProcess.cpp \
	ImageProcessing/SpeckleReductionProcess.cpp \
	ImageProcessing/ColorProcess.cpp \
	ImageProcessing/ParallelImageProcessor.cpp \
	ImageProcessing/ParallelPipelineProfiler.cpp \
	ImageProcessing/PersistenceProcess.cpp \
	ImageProcessing/BSmoothProcess.cpp \
	ImageProcessing/BSpatialFilterProcess.cpp \
	ImageProcessing/BEdgeFilterProcess.cpp \
	ImageProcessing/MFilterProcess.cpp \
	ImageProcessing/EcgProcess.cpp \
	ImageProcessing/DaProcess.cpp \
	ImageProcessing/PwLowPassDecimationFilterProcess.cpp \
	ImageProcessing/DopplerWallFilterProcess.cpp \
	ImageProcessing/DopplerResamplingBuffer.cpp \
	ImageProcessing/DopplerSpectralProcess.cpp \
	ImageProcessing/DopplerSpectralSmoothingProcess.cpp \
	ImageProcessing/DopplerAudioUpsampleProcess.cpp \
	ImageProcessing/DopplerHilbertProcess.cpp \
	ImageProcessing/DopplerPeakEstimator.cpp \
	ImageProcessing/DopplerPeakMaxProcess.cpp \
	ImageProcessing/DopplerPeakMeanProcess.cpp \
	ImageProcessing/DopplerPeakMeanPreProcess.cpp \
	ImageProcessing/DopplerPeakMeanPostProcess.cpp \
	ImageProcessing/DopplerPeakMeanProcessHandler.cpp \
	ImageProcessing/CwBandPassFilterProcess.cpp \
	ImageProcessing/ImageUtils.cpp \
	ImageProcessing/SpatialCompoundProcess.cpp \
	ImageProcessing/FromRawFileProcess.cpp \
	Rendering/RenderSurface.cpp \
	Rendering/LiveRenderSurface.cpp \
	Rendering/Renderer.cpp \
	Rendering/BModeRenderer.cpp \
	Rendering/CModeRenderer.cpp \
	Rendering/MModeRenderer.cpp \
	Rendering/OverlayRenderer.cpp \
	Rendering/PwModeRenderer.cpp \
	Rendering/ScrollModeRenderer.cpp \
	Rendering/WaveformRenderer.cpp \
	Rendering/WaveformTexRenderer.cpp \
	Rendering/OverlayHRRenderer.cpp \
	Rendering/ScanConverterHelper.cpp \
	Rendering/AudioBuffer.cpp \
	Rendering/ThorAudioPlayer.cpp \
	Rendering/AudioCommon.cpp \
	Rendering/AudioDownSampler.cpp \
	Rendering/AudioCubicReSampler.cpp \
	Rendering/ClipEncoderCore.cpp \
	Rendering/OffScreenRenderSurface.cpp \
	Rendering/imgui/imgui.cpp \
	Rendering/imgui/imgui_draw.cpp \
	Rendering/imgui/imgui_demo.cpp \
	Rendering/imgui/imgui_widgets.cpp \
	Rendering/imgui/imgui_tables.cpp \
	Rendering/imgui/imgui_impl_opengl3.cpp \
	Rendering/ImguiRenderer.cpp \
	Rendering/VideoPlayerGL.cpp \
	api/ApiManager.cpp \
	api/ApiCalculator.cpp \
	ScanConverterCl.cpp \
	OpenCLShim.cpp \
	ViewMatrix3x3.cpp \
	UpsReader.cpp \
	DBWrappers.cpp \
	CineBuffer.cpp \
	CineViewer.cpp \
	CinePlayer.cpp \
	CineRecorder.cpp \
	UltrasoundManager.cpp \
	UltrasoundEncoder.cpp \
	ThorFileProcessor.cpp \
	ThorCapnpTypes.capnp.c++ \
	ThorCapnpSerialize.cpp \
	Filesystem.cpp \
	jni/OnLoad.cpp \
	jni/ManagerJni.cpp \
	jni/DauJni.cpp \
	jni/ViewerJni.cpp \
	jni/PlayerJni.cpp \
	jni/RecorderJni.cpp \
	jni/EncoderJni.cpp \
	jni/PuckJni.cpp \
	jni/EFWorkflowJni.cpp \
	jni/BladderWorkflowJni.cpp \
	jni/ThorClipJni.cpp \
	jni/MLManagerJNI.cpp \
	jni/AutoControlJni.cpp \
	AI/CatmullRom.cpp \
	AI/AIManager.cpp  \
	AI/EFWorkflow.cpp \
	AI/EFWorkflowTasks.cpp \
	AI/EFNativeJNI.cpp \
	AI/PhaseDetection.cpp \
	AI/LVSegmentation.cpp \
	AI/EFQualitySubviewConfig.cpp \
	AI/EFQualitySubviewTask.cpp \
	AI/CardiacAnnotator.cpp \
	AI/CardiacAnnotatorTask.cpp \
	AI/PLAXPipeline.cpp \
	AI/YoloBuffer.cpp \
	AI/FASTObjectDetectorModel.cpp \
	AI/FASTObjectDetectorTask.cpp \
	AI/FASTYoloBuffer.cpp \
	AI/VTICalculation.cpp \
    AI/VTICalculationTask.cpp \
    AI/RealtimeModule.cpp \
    AI/AutoDopplerPWAnnotator.cpp \
    AI/AutoDopplerPWYoloBuffer.cpp \
    AI/TDIAnnotator.cpp \
    AI/TDIYoloBuffer.cpp \
    AI/GuidanceJNI.cpp \
	AI/Guidance/PhraseMap.cpp \
	AI/Guidance/AnimationMap.cpp \
	AI/Guidance/GuidanceDisplay.cpp \
	AI/Guidance/GuidanceTypes.cpp \
	AI/AutoPreset/AutoDepthGainPresetTask.cpp \
	AI/AutoPreset/AutoControlManager.cpp \
	AI/Bladder/BladderSegmentationTask.cpp \
	Media/MediaDecoder.cpp \
	Media/YUVFrame.cpp \
	Media/Video.cpp \
	MimicAutoController.cpp

emu_sources := \
	dau/DauSignalHandler.cpp \
	ScanConverterCl.cpp \
	ViewMatrix3x3.cpp \
	UltrasoundManager.cpp \
	UltrasoundEncoder.cpp \
	UpsReader.cpp \
	CineBuffer.cpp \
	CineViewer.cpp \
	CinePlayer.cpp \
	CineRecorder.cpp \
	Rendering/RenderSurface.cpp \
	Rendering/LiveRenderSurface.cpp \
	Rendering/Renderer.cpp \
	Rendering/BModeRenderer.cpp \
	Rendering/CModeRenderer.cpp \
	Rendering/MModeRenderer.cpp \
	Rendering/OverlayRenderer.cpp \
	Rendering/WaveformRenderer.cpp \
	Rendering/WaveformTexRenderer.cpp \
	Rendering/OverlayGraphRenderer.cpp \
	Rendering/OverlayHRRenderer.cpp \
	Rendering/ScanConverterHelper.cpp \
	Rendering/AudioBuffer.cpp \
	Rendering/ThorAudioPlayer.cpp \
	Rendering/AudioCommon.cpp \
	Rendering/AudioDownSampler.cpp \
	Rendering/ClipEncoderCore.cpp \
	Rendering/OffScreenRenderSurface.cpp \
	jni/OnLoad.cpp \
	jni/ManagerJni.cpp \
	jni/ViewerJni.cpp \
	jni/PlayerJni.cpp \
	jni/RecorderJni.cpp \
	jni/EncoderJni.cpp \
	ThorFileProcessor.cpp \
	emulated/EmuJni.cpp \
	emulated/EmuDau.cpp \
	emulated/EmuDmaBuffer.cpp
