// =================================================================
// Autogenerated - Do not edit.
// 
// 2018-02-13 15:21:57.290583
// 
// FPGA Build Information
// RevID  : 1
// BuildID: 1
// DateID : 18-01-25
// =================================================================



#pragma once


// ======================================================================
// Module      : ATU Unroll registers.
// Base Address: 0x0
// The ATU registers can be accessed from the wire using user space
// memory reads and writes. The offset is from BAR4. The JSON file only
// covers ATU region 0 for both outbound and inbound transactions.  Add
// 0x200 to the addresses to for each region beyond 0.
// ----------------------------------------------------------------------
// Register    : Outbound Region Control Register 1
#define ATU_OB_CTL1_ADDR               0x00000000
// Field       : type
// Access      : rw
// PCIe transaction type to match.
#define ATU_OB_CTL1_TYPE_BIT           0
#define ATU_OB_CTL1_TYPE_LEN           5
// Field       : attr
// Access      : rw
// PCIe transaction attributes to match.
#define ATU_OB_CTL1_ATTR_BIT           9
#define ATU_OB_CTL1_ATTR_LEN           2
// Field       : irs
// Access      : rw
// Increase region size. When set, the maximum ATU Region size is
// determined by CX_ATU_MAX_REGION_SIZE. Default region size is 64KB.
#define ATU_OB_CTL1_IRS_BIT            13
#define ATU_OB_CTL1_IRS_LEN            1
// ----------------------------------------------------------------------
// Register    : Outbound Region Control Register 2
#define ATU_OB_CTL2_ADDR               0x00000004
// Field       : msg
// Access      : rw
// MSG TLPs (Message Code). When the address of an outbound TLP is
// matched to this region, and the translated TLP TYPE field is Msg or
// MsgD; then the message field of the TLP is changed to the value in
// this register.
#define ATU_OB_CTL2_MSG_BIT            0
#define ATU_OB_CTL2_MSG_LEN            8
// Field       : tag
// Access      : rw
// The substituted TAG field (byte 6) in the outgoing TLP header when
// TAG_SUBSTITUTE_EN is set.
#define ATU_OB_CTL2_TAG_BIT            8
#define ATU_OB_CTL2_TAG_LEN            8
// Field       : tag_substitute_en
// Access      : rw
// When enabled and region address is matched, the iATU substitutes the
// TAG field of the outbound TLP header with the contents of the TAG
// field in this register. The expected usage scenario is translation
// from AXI MWr to Vendor Defined Msg/MsgD. TAG substitution for MWr will
// not occur because this field (byte 6) in the TLP header is the ST
// field. The design does not support ST.
#define ATU_OB_CTL2_TAG_SUBSTITUTE_EN_BIT 16
#define ATU_OB_CTL2_TAG_SUBSTITUTE_EN_LEN 1
// Field       : snp
// Access      : rw
// Serialize Non-Posted Requests. In this mode, when the AXI Bridge is
// populated, same AXI ID Non-Posted Read/Write Requests are transmitted
// on the wire if there are no other same ID Non-Posted Requests
// outstanding.
#define ATU_OB_CTL2_SNP_BIT            20
#define ATU_OB_CTL2_SNP_LEN            1
// Field       : ip
// Access      : rw
// Inhibit TLP Payload Data for TLP's in Matched Region; assign iATU
// region to be TLP without data. When enabled and region address is
// matched, the iATU marks all TLPs as having no payload data by forcing
// the TLP header Fmt[1] bit =0, regardless of the application inputs
// such as slv_wstrb. 1: Fmt[1] =0 so that only TLP type without data is
// sent. For example, a Msg instead of MsgD will be sent. 0: Fmt[1] =0/1
// so that TLPs with or without data can be sent.
#define ATU_OB_CTL2_IP_BIT             22
#define ATU_OB_CTL2_IP_LEN             1
// Field       : hse
// Access      : rw
// Header Substitute Enable. When enabled and region address is matched,
// the iATU fully substitutes bytes 8-11 (for 3 DWORD header) or bytes
// 12-15 (for 4 DWORD header) of the outbound TLP header with the
// contents of the LWR_TARGET_RW field in
// IATU_LWR_TARGET_ADDR_OFF_OUTBOUND_i. 1: LWR_TARGET_RW in the
// iATU_LWR_TARGET_ADDR_OFF_OUTBOUND_i register is used to fill bytes
// 8-to-11 (for 3 DWORD header) or bytes 12-to-15 (for 4 DWORD header) of
// the translated TLP header. 0: LWR_TARGET_RW in the
// iATU_LWR_TARGET_ADDR_OFF_OUTBOUND_i register forms the new address of
// the translated region.
#define ATU_OB_CTL2_HSE_BIT            23
#define ATU_OB_CTL2_HSE_LEN            1
// Field       : csm
// Access      : rw
// CFG Shift Mode. The iATU uses bits [27:12] of the untranslated address
// (on the XALI0/1/2 interface or AXI slave interface address) to form
// the BDF number of the outgoing CFG TLP. This supports the Enhanced
// Configuration Address Mapping (ECAM) mechanism (Section 7.2.2 of the
// PCI Express Base 3.1 Specification, revision 1.0) by allowing all
// outgoing I/O and MEM TLPs (that have been translated to CFG) to be
// mapped from memory space into any 256 MB region of the PCIe
// configuration space.
#define ATU_OB_CTL2_CSM_BIT            28
#define ATU_OB_CTL2_CSM_LEN            1
// Field       : invert
// Access      : rw
// Invert Mode. When set the address matching region is inverted.
// Therefore, an address match occurs when the untranslated address is in
// the region outside the defined range (Base Address to Limit Address).
#define ATU_OB_CTL2_INVERT_BIT         29
#define ATU_OB_CTL2_INVERT_LEN         1
// Field       : enable
// Access      : rw
// Region Enable. This bit must be set to '1' for address translation to
// take place.
#define ATU_OB_CTL2_ENABLE_BIT         31
#define ATU_OB_CTL2_ENABLE_LEN         1
// ----------------------------------------------------------------------
// Register    : ATU Outbound Base Address Register
#define ATU_OB_BASE_ADDR               0x00000008
// Field       : base
// Access      : rw
// The CX_ATU_MIN_REGION_SIZE configuration parameter (Value Range: 4 kB,
// 8 kB, 16 kB, 32 kB, 64 kB defaults to 64 kB) specifies the minimum
// size of an address translation region. For example, if set to 64 kB;
// the lower 16 bits of the Base, Limit and Target registers are zero and
// all address regions are aligned on 64 kB boundaries. More precisely,
// the lower log2(CX_ATU_MIN_REGION_SIZE) bits are zero.
#define ATU_OB_BASE_BASE_BIT           16
#define ATU_OB_BASE_BASE_LEN           16
// ----------------------------------------------------------------------
// Register    : ATU Region Limit Register
#define ATU_OB_LIMIT_ADDR              0x00000010
// Field       : base
// Access      : rw
// Forms upper bits of the end address of the address region to be
// translated.
#define ATU_OB_LIMIT_BASE_BIT          16
#define ATU_OB_LIMIT_BASE_LEN          16
// ----------------------------------------------------------------------
// Register    : ATU Target Lo Address Register
// When HEADER_SUBSTITUTE_EN in IATU_REGION_CTRL_2_OFF_OUTBOUND_ is '0'
// (normal operation): LWR_TARGET_RW[31:n] forms MSB's of the Lower
// Target part of the new address of the translated region;
// LWR_TARGET_RW[n-1:0] are not used. (The start address must be aligned
// to a CX_ATU_MIN_REGION_SIZE kB boundary, so the lower bits of the
// start address of the new address of the translated region (bits n-1:0)
// are always '0'). n is log2(CX_ATU_MIN_REGION_SIZE). When
// HEADER_SUBSTITUTE_EN in IATU_REGION_CTRL_2_OFF_OUTBOUND_i is '1':
// LWR_TARGET_RW[31:0] forms bytes 8-11 (for 3 dword header) or bytes
// 12-15 (for 4 dword header) of the outbound TLP header. Usage scenarios
// include the transmission of Vendor Defined Messages where the
// controller determines the content of bytes 12 to 15 of the TLP header.
#define ATU_OB_TRGT_LO_ADDR            0x00000014
#define ATU_OB_TRGT_LO_BIT             0
#define ATU_OB_TRGT_LO_LEN             32
// ----------------------------------------------------------------------
// Register    : ATU Target Hi Address Register
// Forms bits [63:32] of the start address (Upper Target part) of the new
// address of the translated region.
#define ATU_OB_TRGT_HI_ADDR            0x00000018
#define ATU_OB_TRGT_HI_BIT             0
#define ATU_OB_TRGT_HI_LEN             32
// ----------------------------------------------------------------------
// Register    : Inbound Region Control Register 1
#define ATU_IB_CTL1_ADDR               0x00000100
// Field       : type
// Access      : rw
// PCIe transaction type to match.
#define ATU_IB_CTL1_TYPE_BIT           0
#define ATU_IB_CTL1_TYPE_LEN           5
// Field       : attr
// Access      : rw
// PCIe transaction attributes to match.
#define ATU_IB_CTL1_ATTR_BIT           9
#define ATU_IB_CTL1_ATTR_LEN           2
// Field       : irs
// Access      : rw
// Increase region size. When set, the maximum ATU Region size is
// determined by CX_ATU_MAX_REGION_SIZE. Default region size is 64KB.
#define ATU_IB_CTL1_IRS_BIT            13
#define ATU_IB_CTL1_IRS_LEN            1
// ----------------------------------------------------------------------
// Register    : Inbound Region Control Register 2
#define ATU_IB_CTL2_ADDR               0x00000104
// Field       : msg
// Access      : rw
// MSG TLPs: (Message Code). When the TYPE field of an inbound Msg/MsgD
// TLP is matched to this value, then address translation proceeds (when
// all other enabled field-matches are successful). This check is only
// performed if the Message Code Match Enable bit of the iATU Control 2
// Register is set.
#define ATU_IB_CTL2_MSG_BIT            0
#define ATU_IB_CTL2_MSG_LEN            8
// Field       : bar
// Access      : rw
// BAR Number. When the BAR number of an inbound MEM or IO TLP that is
// matched by the normal internal BAR address matching mechanism is the
// same as this field, address translation proceeds (when all other
// enabled field-matches are successful). This check is only performed if
// the Match Mode bit of the iATU Control 2 Register is set. 000b - BAR0
// 001b - BAR1 010b - BAR2 011b - BAR3 100b - BAR4 101b - BAR5 110b - ROM
// 111b - reserved IO translation would require either 00100b or 00101b
// in the inbound TLP TYPE; the BAR Number set in the range 000b - 101b
// and that BAR configured as an IO BAR.
#define ATU_IB_CTL2_BAR_BIT            8
#define ATU_IB_CTL2_BAR_LEN            3
// Field       : mtmm
// Access      : rw
// Message Type Match Mode. When enabled, and if single address location
// translate enable is set, then inbound TLPs of type MSG/MSGd which
// match the type field of the iatu_region_ctrl_1_OFF_inbound register
// (=>TYPE[4:3]=2'b10) will be translated. Message type match mode
// overrides any value of MATCH_MODE field in this register. Usage
// scenarios for this are translation of VDM or ATS messages when AXI
// bridge is configured on client interface.
#define ATU_IB_CTL2_MTMM_BIT           13
#define ATU_IB_CTL2_MTMM_LEN           1
// Field       : atm
// Access      : rw
// ATTR Match Enable. Ensures that a successful ATTR TLP field comparison
// match (see ATTR field of the iATU Control 1 Register) occurs for
// address translation to proceed.
#define ATU_IB_CTL2_ATM_BIT            16
#define ATU_IB_CTL2_ATM_LEN            1
// Field       : mcm
// Access      : rw
// Message Code Match Enable (Msg TLPS). Ensures that a successful
// message Code TLP field comparison match (see Message Code field of the
// iATU Control 2 Register) occurs (in MSG transactions) for address
// translation to proceed.
#define ATU_IB_CTL2_MCM_BIT            21
#define ATU_IB_CTL2_MCM_LEN            1
// Field       : salt
// Access      : rw
// Single Address Location Translate Enable. When enabled, Rx TLPs can be
// translated to a single address location as determined by the target
// address register of the iATU region. The main usage scenario is
// translation of Messages (such as Vendor Defined or ATS Messages) to
// MWr TLPs when the AXI bridge is enabled.
#define ATU_IB_CTL2_SALT_BIT           23
#define ATU_IB_CTL2_SALT_LEN           1
// Field       : rc
// Access      : rw
// Response Code. Defines the type of response to give for accesses
// matching this region. This overrides the normal RADM filter response.
// Note that this feature is not available for any region where Single
// Address Location Translate is enabled. 00 - Normal RADM filter
// response is used. 01 - Unsupported request (UR) 10 - Completer abort
// (CA) 11 - Not used / undefined / reserved.
#define ATU_IB_CTL2_RC_BIT             24
#define ATU_IB_CTL2_RC_LEN             2
// Field       : fuzzy
// Access      : rw
// Fuzzy Type Match Mode. When enabled, the iATU relaxes the matching of
// the TLP TYPE field against the expected TYPE field so that CfgRd0 and
// CfgRd1 TLPs are seen as identical. Similarly with CfgWr0 and CfgWr1.
// MWr, MRd and MRdLk TLPs are seen as identical The Routing field of
// Msg/MsgD TLPs is ignored FetchAdd, Swap and CAS are seen as identical.
#define ATU_IB_CTL2_FUZZY_BIT          27
#define ATU_IB_CTL2_FUZZY_LEN          1
// Field       : csm
// Access      : rw
// CFG Shift Mode. This is useful for CFG transactions where the PCIe
// configuration mechanism maps bits [27:12] of the address to the
// bus/device and function number. This allows a CFG configuration space
// to be located in any 256MB window of your application memory space
// using a 28-bit effective address. Shifts bits [31:16] of the
// untranslated address to form bits [27:12] of the translated address.
#define ATU_IB_CTL2_CSM_BIT            28
#define ATU_IB_CTL2_CSM_LEN            1
// Field       : invert
// Access      : rw
// Invert Mode. When set the address matching region is inverted.
// Therefore, an address match occurs when the untranslated address is in
// the region outside the defined range (Base Address to Limit Address).
#define ATU_IB_CTL2_INVERT_BIT         29
#define ATU_IB_CTL2_INVERT_LEN         1
// Field       : mode
// Access      : rw
// Match Mode. Determines Inbound matching mode for TLPs. The mode
// depends on the type of TLP that is received as follows: For MEM-I/O
// TLPs, this field is interpreted as follows: 0: Address Match Mode. The
// iATU operates using addresses as in the outbound direction. The Region
// Base and Limit Registers must be setup. 1:BAR Match Mode. BAR matching
// is used. The BAR Number field is relevant. Not used for RC. For CFG0
// TLPs, this field is interpreted as follows: 0: Routing ID Match Mode.
// The iATU interprets the Routing ID (Bytes 8 to 11 of TLP header) as an
// address. This corresponds to the upper 16 bits of the address in
// MEM-I/O transactions. The Routing ID of the TLP must be within the
// base and limit of the iATU region for matching to proceed. 1: Accept
// Mode. The iATU accepts all CFG0 transactions as address matches. The
// routing ID in the CFG0 TLP is ignored. This is useful as all received
// CFG0 TLPs should be processed regardless of the Bus number. For
// MSG/MSGD TLPs, this field is interpreted as follows: 0: Address Match
// Mode. The iATU treats the third dword and fourth dword of the inbound
// MSG/MSGD TLP as an address and it is matched against the Region Base
// and Limit Registers. 1: Vendor ID Match Mode. This mode is relevant
// for ID-routed Vendor Defined Messages. The iATU ignores the Routing ID
// (Bus, Device, Function) in bits [31:16] of the third dword of the TLP
// header, but matches against the Vendor ID in bits [15:0] of the third
// dword of the TLP header. Bits [15:0] of the Region Upper Base register
// should be programmed with the required Vendor ID. The lower Base and
// Limit Register should be programmed to translate TLPs based on vendor
// specific information in the fourth dword of the TLP header. If
// SINGLE_ADDRESS_LOCATION_TRANSLATE_EN = 1 AND MSG_TYPE_MATCH_MODE = 1,
// then Match Mode is ignored.
#define ATU_IB_CTL2_MODE_BIT           30
#define ATU_IB_CTL2_MODE_LEN           1
// Field       : enable
// Access      : rw
// Region Enable. This bit must be set to '1' for address translation to
// take place.
#define ATU_IB_CTL2_ENABLE_BIT         31
#define ATU_IB_CTL2_ENABLE_LEN         1
// ----------------------------------------------------------------------
// Register    : ATU Inbound Base Lo Address Register
#define ATU_IB_BASE_LO_ADDR            0x00000108
// Field       : base
// Access      : rw
// The CX_ATU_MIN_REGION_SIZE configuration parameter (Value Range: 4 kB,
// 8 kB, 16 kB, 32 kB, 64 kB defaults to 64 kB) specifies the minimum
// size of an address translation region. For example, if set to 64 kB;
// the lower 16 bits of the Base, Limit and Target registers are zero and
// all address regions are aligned on 64 kB boundaries. More precisely,
// the lower log2(CX_ATU_MIN_REGION_SIZE) bits are zero.
#define ATU_IB_BASE_LO_BASE_BIT        16
#define ATU_IB_BASE_LO_BASE_LEN        16
// ----------------------------------------------------------------------
// Register    : ATU Inbound Base Hi Address Register
// Forms bits [63:32] of the start (and end) address of the address
// region to be translated.
#define ATU_IB_BASE_HI_ADDR            0x0000010c
#define ATU_IB_BASE_HI_BIT             0
#define ATU_IB_BASE_HI_LEN             32
// ----------------------------------------------------------------------
// Register    : ATU Inbound Region Limit Register
#define ATU_IB_LIMIT_ADDR              0x00000110
// Field       : base
// Access      : rw
// Forms upper bits of the end address of the address region to be
// translated.
#define ATU_IB_LIMIT_BASE_BIT          16
#define ATU_IB_LIMIT_BASE_LEN          16
// ----------------------------------------------------------------------
// Register    : ATU Target Address Register
#define ATU_IB_TRGT_ADDR               0x00000114
// Field       : base
// Access      : rw
// Forms MSB's of the Lower Target part of the new address of the
// translated region. These bits are always '0'. Field size depends on
// log2(CX_ATU_MIN_REGION_SIZE) in address match mode. Field size depends
// on log2(BAR_MASK+1) in BAR match mode.
#define ATU_IB_TRGT_BASE_BIT           16
#define ATU_IB_TRGT_BASE_LEN           16


